# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8f8b671043dfc4a8d761aab2857bea44b8a1e96376d36c05c026f63848dcbd9f9d7319fbd61b058797a098f0be9617826c778ac482470b5e55208b811a3eaa

test:
  secret_key_base: f4c2454a6a68a4a5e99e7f5b40ed2a35828b14407c810fde47a27f3bf3c14bceb03065fe5fc9c9f83645d116bb3d5b50314616d97103b5ae5369dda11863e00c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
